# Generated by Django 4.0.3 on 2024-06-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0002_payroll_remove_employee_qr_path_employee_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
