# Generated by Django 4.0.3 on 2024-06-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0005_remove_payslip_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
