# Generated by Django 4.0.3 on 2024-06-02 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0006_payslip_deductions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='deductions',
        ),
    ]
