# Generated by Django 4.0.3 on 2024-06-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0008_payroll_professional_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='professional_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
