# Generated by Django 4.0.3 on 2024-06-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0014_alter_employee_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='user',
        ),
    ]
