# Generated by Django 4.0.3 on 2024-06-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0015_rename_username_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='professional_tax',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='gross_pay',
        ),
        migrations.AlterField(
            model_name='payslip',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
