# Generated by Django 4.0.3 on 2024-06-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0017_payroll_professional_tax_payslip_gross_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
