# Generated by Django 4.0.3 on 2024-06-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0018_alter_payslip_gross_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='professional_tax',
        ),
    ]
