# Generated by Django 4.0.3 on 2024-06-02 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0019_remove_payroll_professional_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='pay_period',
        ),
        migrations.AddField(
            model_name='payroll',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payroll',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
