# Generated by Django 4.0.3 on 2024-06-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0021_employee_user_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
