# Generated by Django 4.0.3 on 2024-06-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0022_attendance_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='hours_worked',
        ),
    ]
