# Generated by Django 4.0.3 on 2024-06-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0023_remove_attendance_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='net_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
