# Generated by Django 4.0.3 on 2024-06-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0024_alter_payslip_net_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
