# Generated by Django 4.0.3 on 2024-06-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0026_facialdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacialData',
        ),
    ]
