# Generated by Django 4.0.3 on 2024-06-11 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0027_delete_facialdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facial-data/')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facial_data', to='eqrApp.employee')),
            ],
        ),
    ]
